sudo: false

language: android
android:
  components:
    - platform-tools
    - tools

    - build-tools-23.0.2

    - android-23

    - extra-android-m2repository

install:
   - true

script:
  - ./gradlew build

notifications:
  slack:
    rooms:
      - cloud-timer:RqzjC57tsHmHYhUa66B4Hxj4#notifications