sudo: false

language: android
android:
  components:
    - platform-tools
    - tools

    - build-tools-23.0.2

    - android-23

    - extra-android-m2repository

    - sys-img-armeabi-v7a-android-16

install:
   - true
   - ./gradlew assemble

before_script:
   - echo no | android create avd --force -n test -t android-16 --abi armeabi-v7a
   - emulator -avd test -no-skin -no-audio -no-window &
   - android-wait-for-emulator
   - sleep 30
   - adb shell input keyevent 82

script:
  - ./gradlew build
  - ./gradlew connectedDebugAndroidTest

notifications:
  slack:
    rooms:
      - cloud-timer:RqzjC57tsHmHYhUa66B4Hxj4#notifications